import type { Metadata } from "next";
// import localFont from "next/font/local";
import StyledComponentsRegystry from "@/lib/registry";
import { GlobalStyle } from "@/styles/global";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegystry>
        <GlobalStyle />
        <body>{children}</body>
      </StyledComponentsRegystry>
    </html>
  );
}
