import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";

import "../styles/global.css";
import StyledComponentsRegystry from "@/lib/registry";
import { GlobalStyle } from "@/styles/global";

import Header from "@/components/Header";
import BackgroundCarousel from "./../components/BackgroundCarousel";
import { getImages } from "@/utils/getImages";

const InriaSans = Inria_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Office Garage Custom",
  description: "Generated by create next app",
};

const images = getImages();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={InriaSans.className}>
        <StyledComponentsRegystry>
          <link rel="icon" href="/favicon.jpg" />
          <GlobalStyle />
          <BackgroundCarousel images={images} />
          <Header />
          {children}
        </StyledComponentsRegystry>
      </body>
    </html>
  );
}
